upstream erpnext-gunicorn {
    server erpnext-web:8000;
}

upstream erpnext-socketio {
    server erpnext-websocket:9000;
}

server {
    listen 80;
    server_name localhost;

    # Все real-time события умного дома и видеонаблюдения
    location /socket.io {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host visiontech;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_pass http://erpnext-socketio;
    }

    # Обычный веб-интерфейс и ассеты
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host visiontech;
        
        proxy_redirect off;
        proxy_pass http://erpnext-gunicorn;
    }
}